{{- define "fortio" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.name }}
spec:
  ports:
  - name: http-echo
    port: 8080
    protocol: TCP
  - name: grpc-ping
    port: 8079
    protocol: TCP
  - name: tcp-echo
    port: 8078
    protocol: TCP
  - name: http-echoa
    port: 8077
    protocol: TCP
  - name: grpc-pinga
    port: 8076
    protocol: TCP
  - name: nighthawk-service
    port: 9999
    protocol: TCP
  - name: fortio-reporting
    port: 9076
    protocol: TCP
  selector:
    app: {{ $.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.name }}
  name: {{ $.name }}
spec:
  replicas: {{ $.V.replica }}
  selector:
    matchLabels:
      app: {{ $.name }}
  template:
    metadata:
      annotations:
        {{- if $.Values.interceptionMode }}
        sidecar.istio.io/interceptionMode: {{ $.Values.interceptionMode }}
        {{- end }}
        {{- if eq $.name "fortioclient" }}
        {{- if $.Values.excludeOutboundIPRanges}}
        traffic.sidecar.istio.io/excludeOutboundIPRanges: {{ $.Values.excludeOutboundIPRanges }}
        {{- end }}
        {{- if $.Values.includeOutboundIPRanges }}
        traffic.sidecar.istio.io/includeOutboundIPRanges: {{ $.Values.includeOutboundIPRanges }}
        {{- end }}
        {{- end }}
        sidecar.istio.io/inject: "{{ $.V.inject }}"
        linkerd.io/inject: "{{ $.V.injectL }}"
{{- if eq $.V.injectL "enabled" }}
        config.linkerd.io/skip-outbound-ports: "8077"
        config.linkerd.io/skip-inbound-ports: "8077"
{{- end }}
        # exclude inbound ports of the uncaptured container
        traffic.sidecar.istio.io/excludeInboundPorts: "8076,8077,8078,8081,9999"
        traffic.sidecar.istio.io/excludeOutboundPorts: "80,8076,8077,8078, 8081"
        sidecar.istio.io/proxyCPU: {{ $.Values.proxy.cpu }}
        sidecar.istio.io/proxyMemory: {{ $.Values.proxy.memory }}
      labels:
        app: {{ $.name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: 
{{- if eq $.name "fortioclient" }}
                - "fortioserver"
{{- else }}
                - "fortioclient"
{{- end }}
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: captured
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/fortio
        image:  {{ $.Values.fortioImage }}
{{- if eq $.name "fortioclient" }}
        args:
        - report
{{- else }}
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8079
          protocol: TCP
        - containerPort: 8078
          protocol: TCP
{{- end }}
        resources:
{{- if $.Values.appresources1 }}
{{ toYaml $.Values.appresources1 | indent 10 }}
{{- end }}
      - name: shell
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/fortio
        image: {{ $.Values.curlImage }}
        args:
        - /bin/sleep
        - 3650d
      - name: uncaptured
{{- if eq $.name "fortioclient" }}
        image: {{ $.Values.fortioImage }}
        args:
        - report
        - -http-port
        - "8077"
        - -grpc-port
        - "8076"
        - -redirect-port
        - "8081"
        - -tcp-port
        - "8078"
{{- else }}
        image: {{ $.Values.fortioImage }}
        args:
        - server
        - -http-port
        - "8077"
        - -grpc-port
        - "8076"
        - -tcp-port
        - "8078"
        - -redirect-port
        - "8081"
{{- end }}
        resources:
{{- if $.Values.appresources1 }}
{{ toYaml $.Values.appresources1 | indent 10 }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.name }}
spec:
  hosts:
  - {{ $.name }}.{{ $.Values.domain }}
  gateways:
  - {{ $.Values.gateway }}
  http:
  - route:
    - destination:
        host: {{ $.name }}
        port:
          number: 8080
{{- end }}

{{- $fortioserver := dict "name" "fortioserver" "Values" .Values "V" .Values.server}}
{{- template "fortio" $fortioserver }}
{{- $fortioclient := dict "name" "fortioclient" "Values" .Values "V" .Values.client }}
{{- template "fortio" $fortioclient }}

---
{{- if or $.Values.server.inject $.Values.client.inject }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - fortioserver.{{ .Values.domain }}
    - fortioclient.{{ .Values.domain }}
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - '*'
    port:
      name: https-fortio
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---
{{- end }}
{{- if $.Values.cert }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fortio-two-pod
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs-fortio-twopod
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: fortioclient.{{ .Values.domain }}
  dnsNames:
  - fortioclient.{{ .Values.domain }}
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - fortiotls.{{ .Values.domain }}
      - fortioclient.{{ .Values.domain }}
{{- end }}
