# for client side setting, IP Ranges is server side service or pod
excludeOutboundIPRanges: ""
includeOutboundIPRanges: ""

appresources: {}

proxy:
  cpu: "1000m"
  memory: "512Mi"

appresources1:
  requests:
    cpu: "1500m"
    memory: "1000Mi"

fortioImage: fortio/fortio:latest_release
curlImage: cfmanteiga/alpine-bash-curl-jq:latest
domain: local
gateway: fortio-gateway

server:  # server overrides
  #tlsmode: DISABLE
  tlsmode: ISTIO_MUTUAL
  inject: "false"
  injectL: "disabled" # "enabled" or "disabled"
  replica: 1    # default value

client: # client overrides
  #tlsmode: DISABLE
  tlsmode: ISTIO_MUTUAL
  inject: "false"
  injectL: "disabled" # "enabled" or "disabled"
  replica: 1    # default value

cert: false
interceptionMode: REDIRECT

namespace: ""
loadGenType: ""
